server:
  port: 8080

spring:
  config:
    import: optional:configserver:http://localhost:8888

  application:
    name: msvc-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: chambers
          uri: http://localhost:8090
          predicates:
            - Path=/api/chamber/**

        - id: courses
          uri: http://localhost:9090
          predicates:
            - Path=/api/course/**
